### ISSUE TITLE
Shulkers lose items on explosion

### ISSUE THREAD

**Issue by pablogameing4000** [ArkoSammy12/creeper-healing#10]
Whenever a shulker is blown up, none of the items come out and all the items disappear from it when it is regenerated

**Comment by ArkoSammy12** [comment]
> Whenever a shulker is blown up, none of the items come out and all the items disappear from it when it is regenerated

Hello. Are you perhaps using the latest commit, or are you using the latest release on Modrinth?

**Comment by pablogameing4000** [comment]
I'm using the latest 1.19.2 release on Modrinth

**Comment by ArkoSammy12** [comment]
> I'm using the latest 1.19.2 release on Modrinth

Do you have the drop items on explosions for the explosion source?

**Comment by pablogameing4000** [comment]
I have drop items off. Chests always spawn empty, but at least they drop their items instead of wiping them. Shulkers don't drop or respawn with their items, they just respawn empty.

**Comment by ArkoSammy12** [comment]
> I have drop items off. Chests always spawn empty, but at least they drop their items instead of wiping them. Shulkers don't drop or respawn with their items, they just respawn empty.

I was able to reproduce. I should hopefully get a fix going in the next update of the mod. Thanks for reporting
