### ISSUE TITLE
Lower fabric-loader dependency for 1.20.4

### ISSUE THREAD

**Issue by zachbryant** [ArkoSammy12/creeper-healing#11]
Any chance the fabric loader dep can be lowered? I'm using Arclight which can be tricked into 1.15.9 but not 1.15.10+. Still looking into how I might make 1.15.10 work if possible

**Comment by Linguardium** [comment]
have you tried using the dependency override option for fabric modloader to remove the loader dep version for testing/compatibility on your side? https://fabricmc.net/wiki/tutorial:dependency_overrides
