### ISSUE TITLE
Modrinth Website is 404 and Discord link is invalid

### ISSUE THREAD

**Issue by ToasterUwU** [ArkoSammy12/creeper-healing#14]
Love the mod, exactly what i was looking for. 

But the only reason i found it is because i found it as a search result, which only lead me to a 404 page missing site on modrinth, so i checked on the wayback machine and used that archived version to get here. 

Why is the modrinth project deleted? Why is the discord server invite invalid?

**Comment by ArkoSammy12** [comment]
Hello @ToasterUwU . The modrinth project has been reinstantated. However the Discord link has been removed as I have deleted my discord server.

**Comment by ToasterUwU** [comment]
Thanks! I saw that there already is a 1.21 branch, i think it isnt ready for release yet, but in case it is already i just wanna note that there is no release for it on modrinth yet.

Also, there still is a Discord invite link in the README, so you should probably remove that to avoid confusion

**Comment by ArkoSammy12** [comment]
> Thanks! I saw that there already is a 1.21 branch, i think it isnt ready for release yet, but in case it is already i just wanna note that there is no release for it on modrinth yet.
> 
> Also, there still is a Discord invite link in the README, so you should probably remove that to avoid confusion

Yep. It's just that the new version is using a new configuration library that I made myself, so Im still testing it to make sure that it works right.

I would also like to officially release the library as a mod since Creeper Healing will now depend on it (right now it depends on fabric language kotlin).

Here's the link to the [library](https://github.com/ArkoSammy12/Monkey-Config)

**Comment by ToasterUwU** [comment]
If i can help somehow let me know! And if you can remember and its not too much effort, i would be very happy if you ping me when you release the 1.21 version, would love to instantly install it.

**Comment by ArkoSammy12** [comment]
> Also, there still is a Discord invite link in the README, so you should probably remove that to avoid confusion


Frankly I would love to have a discord but Im not that experienced in creating one xd.

The one that I used to have was pretty much dead.

**Comment by ToasterUwU** [comment]
@ArkoSammy12 Well.. I can help if you want me to! I know my way around Discord very well, since i make Discord Bots, like a lot of them. 

You have my email, so if you interested let me know!
