### ISSUE TITLE
mod showcase?

### ISSUE THREAD

**Issue by Legendmanj** [ArkoSammy12/creeper-healing#15]
Showcase of the mod would be appropriate as it would give proper impression on the mod and how it works

would appreciate it if a showcase video is implemented in the description (;

**Comment by ArkoSammy12** [comment]
I will admit I'm not too familiar with creating showcase videos or gifs, but I'll see what I can come up with xd. Thanks for the suggestion 👍🏻

**Comment by Legendmanj** [comment]
> I will admit I'm not too familiar with creating showcase videos or gifs, but I'll see what I can come up with xd. Thanks for the suggestion 👍🏻

source me when done, ggs! (;
