### ISSUE TITLE
Will this be available for forge anytime soon?

### ISSUE THREAD

**Issue by Otzelix** [ArkoSammy12/creeper-healing#17]
I originally wanted to ask this question over at modrinth, but i was unable to find a comment section there, so i switched over here.

I would love to see an official forge port of this mod, im aware that there is an unofficial one already. but its quite flawed imo.

**Comment by ArkoSammy12** [comment]
> I originally wanted to ask this question over at modrinth, but i was unable to find a comment section there, so i switched over here.
> 
> I would love to see an official forge port of this mod, im aware that there is an unofficial one already. but its quite flawed imo.
> 
> 

Unfortunately, I have no plans to look into porting Creeper Healing or any of my other mods to other mod loaders. If I may ask, I am not aware of any unofficial ports of Creeper Healing to Forge. Would you mind sharing it?


Edit: If you are referring to [this mod](https://github.com/Lothrazar/CreeperHeal), then I should inform you that it has nothing to do with my own mod.

**Comment by ArkoSammy12** [comment]
> I originally wanted to ask this question over at modrinth, but i was unable to find a comment section there, so i switched over here.
> 
> I would love to see an official forge port of this mod, im aware that there is an unofficial one already. but its quite flawed imo.
> 
> 

Unfortunately I have no plans to look into porting Creeper Healing or any of my other mods to other mod loaders. If I may ask, I am nor aware of any unofficial ports of Creeper Healing to Forge. Would you mind sharing it?

**Comment by Otzelix** [comment]
Very sad to hear, but oh well, ill find a work around. And yes, i was talking about that mod

**Comment by ArkoSammy12** [comment]
> Very sad to hear, but oh well, ill find a work around. And yes, i was talking about that mod

You can try using [Sinytra Connector](https://modrinth.com/mod/connector) and see if it is compatible with my mod.
