### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Otzelix** [ArkoSammy12/creeper-healing#19]
How would i go about making the mod regenerate modded explosions, like from create big cannons and such?
Im sadly stuck with version 0.1.7 too, as thats the latest version sinytra connector supports.

(also, yes, rly sorry about openen this many threads, im gona stop soon, dw)

**Comment by ArkoSammy12** [comment]
> How would i go about making the mod regenerate modded explosions, like from create big cannons and such?
> Im sadly stuck with version 0.1.7 too, as thats the latest version sinytra connector supports.
> 
> (also, yes, rly sorry about openen this many threads, im gona stop soon, dw)

Hello. I'm not really familiar with how Create's modded explosion works. If they use a regular TNT explosion under the hood, then it should be enough to enable healing for TNT explosions. Otherwise, I don't think there is a way to explicitly enable healing for modded explosions as of yet.

**Comment by ArkoSammy12** [comment]
@Otzelix I have released a new [Creeper Healing update](https://modrinth.com/mod/creeper-healing/version/2.0.0-1.21+) that should hopefully fix this issue.

**Comment by Otzelix** [comment]
Oh damn, didnt see that, tysm (: 

(i just realised that this is 1.21 and im 1.20.1, oh well, Im still very excited you implemented my idea so fast tho.)
