### ISSUE TITLE
Disable dropped blocks

### ISSUE THREAD

**Issue by RiftLurker** [ArkoSammy12/creeper-healing#2]
Hey, thanks for this great mod, I really enjoy it.
Can we please get an option to disable dropped blocks on creeper explosions, not to create any blocks out of thin air.

Thank you

**Comment by ArkoSammy12** [comment]
Hello. Just to be clear, would you like a config setting to make creeper explosions not drop any items?

**Comment by ArkoSammy12** [comment]
I've added a new config setting to toggle between letting a creeper explosion drop items or not in the latest [commit](https://github.com/ArkoSammy12/creeper-healing/commit/e47fbe07a0e040eac33a41ac32b62b2aa0f310b8). 

Please let me know if this was the desired feature you wanted in the mod. Thanks :)

**Comment by RiftLurker** [comment]
Thank you, that sounds exactly like what I wanted
