### ISSUE TITLE
Daytime Healing Mode/Config Settings Not Applying

### ISSUE THREAD

**Issue by chill7n** [ArkoSammy12/creeper-healing#20]
I am having issues with some of the settings in the creeper-healing.toml not applying/not applying correctly.

explosion_heal_delay = 1.0
block_placement_delay = 1.0

both of those settings seem to have no effect while the mode is set to "daytime_healing_mode"

you can recreate this by changing the default settings in the config to those values. For reference, I only have 

heal_creeper_explosions = true, 
restore_block_nbt = true
force_blocks_with_nbt_to_always_heal = true

These were tested with both old and new creeper explosions. Another issue I had was that when the explosion occurred during the day, it would begin to heal during the night when "daytime_healing_mode" was enabled. When an explosion occurred at night, it would heal during the day, but it still did not follow the settings I had put in the configuration. You can recreate this by enabling "daytime_healing_mode" and spawning a creeper next to you in survival during the day.

I am also using the Creeper Overhaul mod, if that would cause any issues.

**Comment by ArkoSammy12** [comment]
Hello. I'm sorry for not replying earlier. Indeed, the daytime healing mode is supposed to ignore the settings for block placement delays and explosion heal delays, as the intended feature is that these are taken care of automatically by the mode. Explosions are supposed to start healing during the day, and they are supposed to finish healing just before night time.
