### ISSUE TITLE
Crash when healing double chest and cannot start server again.

### ISSUE THREAD

**Issue by Hippopipo** [ArkoSammy12/creeper-healing#21]
[latest.log](https://mclo.gs/2GgQ6RV) I actually goofed up and this is the latest.log for the second time crash, but i don't think that matters much.
[First time crash log](https://mclo.gs/gzseAFol)
[Second time crash log](https://mclo.gs/buu6yLr)
Could be a mod compatibility issue, but not sure, as i have a bunch of mods installed. If it matters the chest had four flint and steels placed in the corners. Also here is the config: 
[creeper-healing.zip](https://github.com/user-attachments/files/17606383/creeper-healing.zip) had to upload as zip file, as github doesn't support .toml.

**Comment by Hippopipo** [comment]
Actually here is the config file as a gist: [](https://gist.github.com/Hippopipo/f25d6c7262f0fd89fe1b0029483a0e15)

**Comment by Hippopipo** [comment]
https://gist.github.com/Hippopipo/f25d6c7262f0fd89fe1b0029483a0e15

**Comment by Hippopipo** [comment]
I checked this out further, and it appears that this happens because of force_blocks_with_nbt_to_always_heal set to true.

**Comment by ArkoSammy12** [comment]
As of the latest commit in my 1.21.4 branch, I'm not able to reproduce the issue anymore, so I will go ahead and assume I was able to fix it. Thanks for reporting 👍🏻

**Comment by Hippopipo** [comment]
Is it possible to port this fix to 1.21.1?

**Comment by Hippopipo** [comment]
> Is it possible to port this fix to 1.21.1?

@ArkoSammy12
