### ISSUE TITLE
Can you please please please please update this mod to the newest version of 1.21.4

### ISSUE THREAD

**Issue by goganlowell** [ArkoSammy12/creeper-healing#22]
I love your mod akroSammy12  and i have been wanting to update my current modpack to 1.21.4 but i have been holding off as i really want to have you mod in the modpack andi would love it if you could please update it if it isnt too much trouble.
thank you for your time.

Sincerely, TheLoginator200

**Comment by ArkoSammy12** [comment]
Here ya go https://modrinth.com/mod/creeper-healing/version/2.0.2-1.21.4+ :D. Make sure to report any issues if you find any 👍🏻

**Comment by goganlowell** [comment]
omg THANK YOU SO MUCH
