### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by zaBees** [ArkoSammy12/creeper-healing#24]
I've only got the mod and the libraries installed
It also crashes on my server
https://mclo.gs/9BVaSPn

**Comment by ArkoSammy12** [comment]
> I've only got the mod and the libraries installed
> It also crashes on my server
> https://mclo.gs/9BVaSPn

The logs you provided are for Minecraft 1.21.3, and you are using version 2.0.1 of Creeper Healing, which is only compatible with up to version 1.21.1 of the game. I suggest updating your game and/or server to 1.21.4 and using the latest version of Creeper Healing (2.0.2), which is compatible with 1.21.4.

**Comment by zaBees** [comment]
a okey ty :D

**Comment by ArkoSammy12** [comment]
> a okey ty :D 

All good :D
