### ISSUE TITLE
1.19.2 port

### ISSUE THREAD

**Issue by Ricenami** [ArkoSammy12/creeper-healing#4]
Hi!

I love the idea of your mod, but unfortunately me and my friends play on a 1.19.2 server, is there any way you could port to fabric? If its too much trouble I understand.

Cheers!

rice

**Comment by ArkoSammy12** [comment]
Hello @Ricenami . I've made a quick backport to 1.19.2, as it didn't involve many changes to the codebase. However, I cannot guarantee that Creeper Healing for 1.19.2 will be supported indefinitely. Here's the [Modrinth release page](https://modrinth.com/mod/creeper-healing/version/0.1.5-1.19.2).

If you encounter any bugs, please make sure to report them here or in the [Discord server](https://discord.gg/UKr8n3b3ze). I hope you appreciate this backport, and thank you for the suggestion :D.
