### ISSUE TITLE
Crash at load

### ISSUE THREAD

**Issue by jrharris42** [ArkoSammy12/creeper-healing#5]
I'm having this issue with the latest version:

[crash-2023-10-17_19.39.06-client.txt](https://github.com/ArkoSammy12/creeper-healing/files/12969369/crash-2023-10-17_19.39.06-client.txt)

**Comment by ArkoSammy12** [comment]
> I'm having this issue with the latest version:
> 
> [crash-2023-10-17_19.39.06-client.txt](https://github.com/ArkoSammy12/creeper-healing/files/12969369/crash-2023-10-17_19.39.06-client.txt)
> 

Hello. May I take a look at your current configuration file?

**Comment by jrharris42** [comment]
Sure, Ill upload it later.

It definitely seems like going back to the last September version fixes me.  Based on the changelog, that makes sense.  I'll go back to the latest version and if I'm still having trouble I'll send you the file, then rename it and see if the game loads without a config file.

**Comment by ArkoSammy12** [comment]
Make sure that the (new) configuration file contains the section for the replace map, including the little `[replace_map]` header title indicating its section. On a default config, with the last version of the mod, it should be located below all other config sections.

**Comment by jrharris42** [comment]
When I went from the last September version to the first October version, my .toml file was created with 0 bytes in it.  Deleting it and my .json and installing the very latest mod version did the trick.  Thanks!

**Comment by ArkoSammy12** [comment]
> When I went from the last September version to the first October version, my .toml file was created with 0 bytes in it.  Deleting it and my .json and installing the very latest mod version did the trick.  Thanks!
> 
> 

You are welcome! Make sure to post any other issues you might have 👍
